### ISSUE TITLE
How to handle the intents?

### ISSUE THREAD

**Issue by qadir-genetech** [digital-engine/smooch-api-ai-bot#1]
How to handle intent?

Like I have defined the intent `Search Movie` in api.ai dashboard.

**Comment by thowar2** [comment]
The script takes the user message from smooch.io and sends it to api.ai. It will take that natural language and match it with the correct intent, then return the response defined for that intent.

You can see the response object in the api.ai docs: https://docs.api.ai/docs/query#response

**Comment by qadir-genetech** [comment]
You are saying that I should handle the intents in the heroku/index file as you have did?

**Comment by thowar2** [comment]
You will have to figure out how you need it handled for your own needs, this is just a simple connector.

But the purpose of api.ai is to find the correct intent when given natural language, then extract entities if needed, and excute the defined actions.

This repo is quite basic, no support for context, entities, or execution of code. It will only work for simple conversations, but you can expand it as you need!

**Comment by qadir-genetech** [comment]
Thanks for your time
